### ISSUE TITLE
build failure on Raspberry pi3 

### ISSUE THREAD

**Issue by shreeswifty** [CsoundQt/CsoundQt#254]
src/CsoundHtmlOnlyWrapper.cpp: In member function ‘void CsoundHtmlOnlyWrapper::csoundMessageCallback(int, const char*, va_list)’:
src/CsoundHtmlOnlyWrapper.cpp:256:23: error: ‘vasprintf’ is not a member of ‘QString’
     QString message = QString::vasprintf(format, args);
                       ^~~~~~~
src/CsoundHtmlOnlyWrapper.cpp:252:55: warning: unused parameter ‘attributes’ [-Wunused-parameter]
 void CsoundHtmlOnlyWrapper::csoundMessageCallback(int attributes,
                                                       ^~~~~~~~~~
Makefile:1552: recipe for target 'build/doubles/obj/CsoundHtmlOnlyWrapper.o' failed
make: *** [build/doubles/obj/CsoundHtmlOnlyWrapper.o] Error 1

**Comment by tarmoj** [comment]
Thanks for the report!

As I now read from Qt manual http://doc.qt.io/qt-5/qstring.html#vasprintf
QString::vasprintf was introduced in Qt 5.5 and perhaps you have older Qt.
Anyway, this should be changed that the code builds also with older Qt
versions.

I will try to fix it in coming days. So far, if you don't need html-support
per se, I suggest to pull code from master branch or download from release
0.9.5 page, that should work.
https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.5

Greetings,
Tarmo

2017-12-14 7:33 GMT+02:00 shreeswifty <notifications@github.com>:

**Comment by shreeswifty** [comment]
hi 
i already tried to build with 0.95 and the error is the same. Any other suggestions?

**Comment by tarmoj** [comment]
Hi,
The code of 0.9.5 from master branch does not have CsoundHtmlOnlyWrapper
class. Or where does the error happen now? Did you do make clean? Which
options did you use for qmake? What is your qt version?

Tamo


14.12.2017 15:27 kirjutas kuupäeval "shreeswifty" <notifications@github.com

**Comment by tarmoj** [comment]
Hi, 

You never answered about your Qt version but assuming that the Pi might have still Qt4, I checked the code and added some conditions and changes to build the code wit Qt 4 (tested with At 4.8.6) again. it is pushed now to DEVELOP branch, please checkout develop branchm build and  test.

Sorry, I forgot to test against Qt 4 before -  it is Qt 5.10 out there... But of course, it should be supported-

greetings,
tarmo
